import click
import os
import subprocess
import shutil
import secrets
import sys
from pathlib import Path
from importlib import resources


COMPOSE_FILE = "docker-compose.yml"
ENV_FILE = ".env"


def get_template_path(filename):
    """Get the path to a bundled template file."""
    return resources.files("fangcunguard") / "templates" / filename


def copy_template(filename, dest_path):
    """Copy a template file to the destination."""
    source = get_template_path(filename)
    with resources.as_file(source) as src:
        shutil.copy2(src, dest_path)


def run_compose(args, project_dir="."):
    """Run a docker compose command."""
    compose_file = os.path.join(project_dir, COMPOSE_FILE)
    if not os.path.exists(compose_file):
        click.echo("Error: docker-compose.yml not found. Run 'fangcunguard init' first.", err=True)
        sys.exit(1)
    cmd = ["docker", "compose", "-f", compose_file] + args
    return subprocess.run(cmd, cwd=project_dir)


@click.group()
@click.version_option(package_name="fangcunguard")
def cli():
    """Fangcun Guard — Open-Source AI Security Infrastructure"""
    pass


@cli.command()
@click.option("--dir", "project_dir", default=".", help="Directory to initialize in (default: current directory)")
def init(project_dir):
    """Initialize a Fangcun Guard deployment."""
    project_dir = os.path.abspath(project_dir)
    os.makedirs(project_dir, exist_ok=True)

    compose_dest = os.path.join(project_dir, COMPOSE_FILE)
    env_dest = os.path.join(project_dir, ENV_FILE)

    # Check if files already exist
    if os.path.exists(compose_dest):
        if not click.confirm(f"{COMPOSE_FILE} already exists. Overwrite?", default=False):
            click.echo("Skipping docker-compose.yml")
        else:
            copy_template("docker-compose.yml", compose_dest)
            click.echo(f"  Updated {COMPOSE_FILE}")

    else:
        copy_template("docker-compose.yml", compose_dest)
        click.echo(f"  Created {COMPOSE_FILE}")

    if os.path.exists(env_dest):
        if not click.confirm(f"{ENV_FILE} already exists. Overwrite?", default=False):
            click.echo("Skipping .env")
            click.echo()
            click.echo(f"Initialized in {project_dir}")
            return

    # Interactive .env configuration
    click.echo()
    click.echo("Configure your deployment:")
    click.echo("(Press Enter to use default values)")
    click.echo()

    model_api_url = click.prompt(
        "Detection model API URL (OpenAI-compatible)",
        default="http://localhost:58002/v1",
    )
    model_api_key = click.prompt(
        "Detection model API Key",
        default="EMPTY",
    )
    model_name = click.prompt(
        "Detection model name",
        default="Qwen3Guard-Gen-8B",
    )

    admin_email = click.prompt(
        "Admin email",
        default="admin@yourdomain.com",
    )
    admin_password = click.prompt(
        "Admin password",
        default="CHANGE-THIS-PASSWORD-IN-PRODUCTION",
    )

    # Generate secure defaults
    jwt_secret = secrets.token_urlsafe(32)
    pg_password = secrets.token_urlsafe(16)

    env_content = f"""# Fangcun Guard Configuration
# Generated by: fangcunguard init

# ============================================
# Detection Model (REQUIRED)
# ============================================
GUARDRAILS_MODEL_API_URL={model_api_url}
GUARDRAILS_MODEL_API_KEY={model_api_key}
GUARDRAILS_MODEL_NAME={model_name}

# ============================================
# Security
# ============================================
SUPER_ADMIN_USERNAME={admin_email}
SUPER_ADMIN_PASSWORD={admin_password}
JWT_SECRET_KEY={jwt_secret}
POSTGRES_PASSWORD={pg_password}

# ============================================
# Optional — defaults work out of the box
# ============================================
# DEFAULT_LANGUAGE=en
# DEPLOYMENT_MODE=enterprise
# FRONTEND_PORT=3000
# ADMIN_PORT=5000
# DETECTION_PORT=5001
# PROXY_PORT=5002
"""
    with open(env_dest, "w") as f:
        f.write(env_content)
    click.echo(f"  Created {ENV_FILE}")

    click.echo()
    click.echo(f"Initialized in {project_dir}")
    click.echo()
    click.echo("Next steps:")
    click.echo("  fangcunguard up       Start services")
    click.echo("  fangcunguard status   Check service status")


@cli.command()
@click.option("--dir", "project_dir", default=".", help="Project directory")
@click.option("-d", "--detach/--no-detach", default=True, help="Run in background (default: true)")
def up(project_dir, detach):
    """Start Fangcun Guard services."""
    args = ["up"]
    if detach:
        args.append("-d")
    result = run_compose(args, project_dir)
    if result.returncode == 0 and detach:
        click.echo()
        click.echo("Fangcun Guard is starting up.")
        click.echo("  Web UI:    http://localhost:3000/platform/")
        click.echo("  Admin API: http://localhost:5000")
        click.echo("  Proxy API: http://localhost:5002")
        click.echo()
        click.echo("Run 'fangcunguard status' to check service health.")


@cli.command()
@click.option("--dir", "project_dir", default=".", help="Project directory")
@click.option("-v", "--volumes", is_flag=True, default=False, help="Also remove data volumes")
def down(project_dir, volumes):
    """Stop Fangcun Guard services."""
    args = ["down"]
    if volumes:
        args.append("-v")
    run_compose(args, project_dir)


@cli.command()
@click.option("--dir", "project_dir", default=".", help="Project directory")
def status(project_dir):
    """Show service status."""
    run_compose(["ps"], project_dir)


@cli.command()
@click.option("--dir", "project_dir", default=".", help="Project directory")
@click.option("-f", "--follow", is_flag=True, default=False, help="Follow log output")
@click.argument("service", required=False)
def logs(project_dir, follow, service):
    """View service logs."""
    args = ["logs"]
    if follow:
        args.append("-f")
    if service:
        args.append(service)
    run_compose(args, project_dir)


if __name__ == "__main__":
    cli()
