"""Helpers for signing and reading bypass tokens."""

import hmac
import hashlib
import time
from typing import Mapping, Optional, Tuple
from config import settings
from utils.logger import setup_logger

logger = setup_logger()

# Preferred public header name plus legacy aliases kept for compatibility.
BYPASS_TOKEN_HEADER = "X-FangcunGuard-Bypass-Token"
BYPASS_TOKEN_HEADERS = (
    BYPASS_TOKEN_HEADER,
    "X-FG-Bypass-Token",
    "X-OG-Bypass-Token",
)

# Token validity period in seconds (5 minutes).
TOKEN_VALIDITY_SECONDS = 300


def _derive_secret_key() -> bytes:
    """Return the shared signing key for bypass tokens."""
    return settings.jwt_secret_key.encode('utf-8')


def bypass_header_name() -> str:
    """Return the preferred public header for bypass tokens."""
    return BYPASS_TOKEN_HEADER


def read_bypass_token(headers: Mapping[str, str]) -> Optional[str]:
    """Read a bypass token from the preferred header or a legacy alias."""
    for name in BYPASS_TOKEN_HEADERS:
        token = headers.get(name)
        if token:
            return token
    return None


def make_bypass_token(tenant_id: str, request_id: str) -> str:
    """Create a signed bypass token for a request."""
    timestamp = str(int(time.time()))
    message = f"{tenant_id}:{request_id}:{timestamp}"
    signature = hmac.new(
        _derive_secret_key(),
        message.encode('utf-8'),
        hashlib.sha256
    ).hexdigest()
    token = f"{tenant_id}:{request_id}:{timestamp}:{signature}"
    logger.debug(f"Generated bypass token for request {request_id}")
    return token


def parse_bypass_token(token: str) -> Tuple[bool, Optional[str], Optional[str]]:
    """Validate a bypass token and return ``(is_valid, tenant_id, request_id)``."""
    if not token:
        return False, None, None

    try:
        parts = token.split(':')
        if len(parts) != 4:
            logger.warning(f"Invalid bypass token format: expected 4 parts, got {len(parts)}")
            return False, None, None

        tenant_id, request_id, timestamp_str, provided_signature = parts

        try:
            timestamp = int(timestamp_str)
            current_time = int(time.time())

            if current_time - timestamp > TOKEN_VALIDITY_SECONDS:
                logger.warning(f"Bypass token expired: age={(current_time - timestamp)}s > {TOKEN_VALIDITY_SECONDS}s")
                return False, None, None

            if timestamp - current_time > 60:
                logger.warning(f"Bypass token from future: timestamp={timestamp}, current={current_time}")
                return False, None, None

        except ValueError:
            logger.warning(f"Invalid timestamp in bypass token: {timestamp_str}")
            return False, None, None

        message = f"{tenant_id}:{request_id}:{timestamp_str}"
        expected_signature = hmac.new(
            _derive_secret_key(),
            message.encode('utf-8'),
            hashlib.sha256
        ).hexdigest()

        if not hmac.compare_digest(provided_signature, expected_signature):
            logger.warning(f"Invalid bypass token signature for request {request_id}")
            return False, None, None

        logger.info(f"Valid bypass token for request {request_id}, tenant {tenant_id}")
        return True, tenant_id, request_id

    except Exception as e:
        logger.error(f"Error verifying bypass token: {e}")
        return False, None, None
